<a href="https://colab.research.google.com/github/Vishu52/9d9b93d3-2a90-4e7f-96c1-7607df7a178f/blob/main/Numpy_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Python library: collection of reusable modules. Used to avoid rewriting logic.

# 2. NumPy array vs List:
# NumPy arrays are faster, memory efficient, and support vectorization.

# 3. Shape, size, dimension
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

# 4. Access first row
print("First Row:", arr[0])

# 5. Element at 3rd row, 4th column
print("Element:", arr[2, 3])

# 6. Extract all odd-indexed column elements
print("Odd indexed elements:\n", arr[:, 1::2])

# 7. Random 3×3 matrix (0 → 1)
print("Random 3x3:\n", np.random.rand(3, 3))

# 8. rand = uniform distribution; randn = normal distribution

# 9. Increase dimension
expanded = np.expand_dims(arr, axis=0)
print("Expanded dims:\n", expanded)

# 10. Transpose
print("Transpose:\n", arr.T)

# 11. Matrix operations
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

B = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

print("Index-wise multiplication:\n", A * B)
print("Matrix multiplication:\n", A.dot(B.T))
print("Addition:\n", A + B)
print("Subtract:\n", A - B)
print("Division:\n", B / A)

# 12. Swap byte order (NumPy 2.0 compatible)
swapped = A.view(A.dtype.newbyteorder("<"))
print("Byte swapped:\n", swapped)

# 13. Inverse of matrix
M = np.array([[1,2],[3,4]])
print("Inverse:\n", np.linalg.inv(M))

# 14. Reshape
print("Reshaped:\n", arr.reshape(4, 3))

# 15. Broadcasting example
x = np.array([1,2,3])
y = np.array([[10],[20],[30]])
print("Broadcasting result:\n", x + y)


Shape: (3, 4)
Size: 12
Dimensions: 2
First Row: [1 2 3 4]
Element: 12
Odd indexed elements:
 [[ 2  4]
 [ 6  8]
 [10 12]]
Random 3x3:
 [[0.74270862 0.88432487 0.95790456]
 [0.31680131 0.01219421 0.11669718]
 [0.1910352  0.10986945 0.29192774]]
Expanded dims:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtract:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Byte swapped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Reshaped:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Broadcasting result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
